/**
 * Real client marks, lifted from the logoorbit.com portfolio pages.
 *
 * Each entry points at /public/portfolio/<slug>.webp: the logo trimmed to its
 * own bounding box and centred on a 520px white square, so the grid stays even
 * whether a mark is a tall badge or a wide wordmark. The white is part of the
 * artwork, which is why the tiles keep a white face in dark mode too.
 *
 * Where a client has more than one concept in the set, both are kept: they are
 * different pieces of work, not duplicates.
 *
 * The newest marks lead, so the slice the home page shows is the most recent
 * work rather than whatever happened to sit at the top of the old site.
 * `name` is optional: a mark with no legible wordmark is captioned by its
 * industry rather than given an invented company name.
 */
export const portfolioLogos = [
  { slug: 'raven-crux-emblem', name: 'Raven Crux', category: 'Community' },
  { slug: 'footworks-dance-studio', name: 'Footworks Dance Studio', category: 'Fitness' },
  { slug: 'mitten-water', name: 'Mitten Water', category: 'Food & Drink' },
  { slug: 'raven-crux-seal', name: 'Raven Crux', category: 'Community' },
  { slug: 'mitts-on-main', name: "Mitt's on Main", category: 'Food & Drink' },
  { slug: 'raven-crux-monogram', name: 'Raven Crux', category: 'Community' },
  { slug: 'coffee-emblem', name: null, category: 'Food & Drink' },
  { slug: 'revolution-roar', name: "Revolution ROAR", category: 'Real Estate' },
  { slug: 'boomerang', name: "Boomerang", category: 'Retail' },
  { slug: 'air-america-drone', name: "Air America Drone", category: 'Technology' },
  { slug: 'hyper-jackets', name: "Hyper Jackets", category: 'Fashion' },
  { slug: 'faith-in-realty', name: "Faith In Realty", category: 'Real Estate' },
  { slug: 'd-bella-bridal', name: "D'Bella Bridal", category: 'Fashion' },
  { slug: 'chocolat-and-creme-lingerie', name: "Chocolat & Creme Lingerie", category: 'Fashion' },
  { slug: 'fashionably-pregnant', name: "Fashionably Pregnant", category: 'Fashion' },
  { slug: 'lenis-fashion', name: "Lenis Fashion", category: 'Fashion' },
  { slug: 'daisy-sunshine', name: "Daisy Sunshine", category: 'Retail' },
  { slug: 'off-the-wall-diy', name: "Off the Wall DIY", category: 'Retail' },
  { slug: 'mrs-fancie-pants', name: "Mrs Fancie Pants", category: 'Fashion' },
  { slug: 'libas', name: "Libas", category: 'Fashion' },
  { slug: 'lil-diva-s-boutique', name: "Lil Diva's Boutique", category: 'Fashion' },
  { slug: 'rogers-carpet-cleaning', name: "Rogers Carpet Cleaning", category: 'Home Services' },
  { slug: 'universal-cleaning-services', name: "Universal Cleaning Services", category: 'Home Services' },
  { slug: 'rugby-shirts-online', name: "Rugby Shirts Online", category: 'Sports' },
  { slug: 'oxford-sports-massage', name: "Oxford Sports Massage", category: 'Fitness' },
  { slug: 'heavenly-cleanings', name: "Heavenly Cleanings", category: 'Home Services' },
  { slug: 'armand-cleaning-and-management', name: "Armand Cleaning & Management", category: 'Home Services' },
  { slug: 'kidd-friendly-cleaning', name: "Kidd Friendly Cleaning", category: 'Home Services' },
  { slug: 'cleaning-connections', name: "Cleaning Connections", category: 'Home Services' },
  { slug: 'crisp-n-clean', name: "Crisp N Clean", category: 'Home Services' },
  { slug: 'the-jewel-of-cleaning', name: "The Jewel of Cleaning", category: 'Home Services' },
  { slug: 'cleaning-connections-2', name: "Cleaning Connections", category: 'Home Services' },
  { slug: 'dawn-foss-christian-books-and-music', name: "Dawn Foss Christian Books and Music", category: 'Retail' },
  { slug: 'bright-water-pressure-cleaning', name: "Bright Water Pressure Cleaning", category: 'Home Services' },
  { slug: 'luxe-commercial-cleaning', name: "Luxe Commercial Cleaning", category: 'Home Services' },
  { slug: 'high-country-window-cleaning', name: "High Country Window Cleaning", category: 'Home Services' },
  { slug: 'aries-construction', name: "Aries Construction", category: 'Construction' },
  { slug: 'red-plier-carpentery', name: "Red Plier Carpentery", category: 'Construction' },
  { slug: 'tom-s-carpentry', name: "Tom's Carpentry", category: 'Construction' },
  { slug: 'marin-construction', name: "Marin Construction", category: 'Construction' },
  { slug: 'sunlite-solar-and-construction', name: "Sunlite Solar & Construction", category: 'Construction' },
  { slug: 'milvet-construction', name: "MilVet Construction", category: 'Construction' },
  { slug: 'briermine-construction-solutions', name: "Briermine Construction Solutions", category: 'Construction' },
  { slug: 'hallmark-construction-corp', name: "Hallmark Construction Corp", category: 'Construction' },
  { slug: 'stoneway-construction', name: "Stoneway Construction", category: 'Construction' },
  { slug: 'texas-construction', name: "Texas Construction", category: 'Construction' },
  { slug: 'all-built-construction', name: "All Built Construction", category: 'Construction' },
  { slug: 'felix-landscape-and-maintenance', name: "Felix Landscape & Maintenance", category: 'Home Services' },
  { slug: 'kents-mechanical', name: "Kents Mechanical", category: 'Construction' },
  { slug: 'custom-land-development', name: "Custom Land Development", category: 'Real Estate' },
  { slug: 's-e-brown-co', name: "S. E. Brown Co.", category: 'Construction' },
  { slug: 'optimum-personal', name: "Optimum Personal", category: 'Fitness' },
  { slug: 'northland-marine-and-power-sports', name: "Northland Marine and Power Sports", category: 'Sports' },
  { slug: 'oh-baby-fitness', name: "Oh Baby! Fitness", category: 'Fitness' },
  { slug: 'r-a-w-fitness-club', name: "R.A.W. Fitness Club", category: 'Fitness' },
  { slug: 'finesse-fitness', name: "Finesse Fitness", category: 'Fitness' },
  { slug: 'summer-ready-fitness', name: "Summer Ready Fitness", category: 'Fitness' },
  { slug: 'mad-monkey-fitness', name: "Mad Monkey Fitness", category: 'Fitness' },
  { slug: 'zenith-fitness', name: "Zenith Fitness", category: 'Fitness' },
  { slug: 'dedicate-fitness-nutrition', name: "Dedicate Fitness Nutrition", category: 'Fitness' },
  { slug: 'motorsport', name: "Motorsport", category: 'Automotive' },
  { slug: 'mary-poppins-fitness', name: "Mary Poppins Fitness", category: 'Fitness' },
  { slug: 'american-online-archery', name: "American Online Archery", category: 'Sports' },
  { slug: 'kick-in-fitness-2', name: "Kick In Fitness 2", category: 'Fitness' },
  { slug: 'best-fit-by-brazil', name: "Best Fit by Brazil", category: 'Fitness' },
  { slug: 'the-famous-curves', name: "The Famous Curves", category: 'Fashion' },
  { slug: 'south-wales-ironmen', name: "South Wales Ironmen", category: 'Sports' },
  { slug: 'the-soccer-van', name: "The Soccer Van", category: 'Sports' },
  { slug: 'm-and-m-kids-sports', name: "M&M Kids Sports", category: 'Sports' },
  { slug: 'carolina-sports-and-apparel', name: "Carolina Sports and Apparel", category: 'Sports' },
  { slug: 'jpb-sports-video', name: "JPB Sports Video", category: 'Sports' },
  { slug: 'deni-sports-tennis-academy', name: "Deni Sports Tennis Academy", category: 'Sports' },
  { slug: 'deni-sports-tennis-academy-2', name: "Deni Sports Tennis Academy", category: 'Sports' },
  { slug: 'tint-evolution', name: "Tint Evolution", category: 'Automotive' },
  { slug: 'chris-hatanaka-photography', name: "Chris Hatanaka Photography", category: 'Photography' },
  { slug: 'chris-hatanaka-photography-2', name: "Chris Hatanaka Photography", category: 'Photography' },
  { slug: 'joey-taylor-photography', name: "Joey Taylor Photography", category: 'Photography' },
  { slug: 'joey-taylor-photography-2', name: "Joey Taylor Photography", category: 'Photography' },
  { slug: 'dezember-photography', name: "Dezember Photography", category: 'Photography' },
  { slug: 'lauren-leigh-photography', name: "Lauren Leigh Photography", category: 'Photography' },
  { slug: 'murray-golder-photography', name: "Murray Golder Photography", category: 'Photography' },
  { slug: 'joey-taylor-photography-3', name: "Joey Taylor Photography", category: 'Photography' },
  { slug: 'life-sweet-photography', name: "Life Sweet Photography", category: 'Photography' },
  { slug: 'rosewine-photography', name: "RoseWine Photography", category: 'Photography' },
  { slug: 'unik-moments-photography', name: "Unik Moments Photography", category: 'Photography' },
  { slug: 'triton-design-tech', name: "Triton Design Tech", category: 'Technology' },
  { slug: 'cross-tech-solutions', name: "Cross-Tech Solutions", category: 'Technology' },
  { slug: 'otter-technology', name: "Otter Technology", category: 'Technology' },
  { slug: 'pro-tech', name: "Pro Tech", category: 'Automotive' },
  { slug: 'geeky-monkey-technologies', name: "Geeky Monkey Technologies", category: 'Technology' },
  { slug: 'techno18', name: "Techno18", category: 'Technology' },
  { slug: 'tech-enabled-solutions', name: "Tech-Enabled Solutions", category: 'Technology' },
  { slug: 'uniflo-technology', name: "Uniflo Technology", category: 'Technology' },
  { slug: '1op-technologies', name: "1OP Technologies", category: 'Technology' },
  { slug: 'integrated-technical-solutions', name: "Integrated Technical Solutions", category: 'Technology' },
  { slug: 'grayjax-technologies', name: "Grayjax Technologies", category: 'Technology' },
  { slug: 'julvia-technologies', name: "Julvia Technologies", category: 'Technology' },
  { slug: 'kworld-technology-solutions', name: "KWorld Technology Solutions", category: 'Technology' },
  { slug: 'techhead', name: "TechHead", category: 'Technology' },
  { slug: 'kworld-technology-solutions-2', name: "KWorld Technology Solutions", category: 'Technology' },
  { slug: 'one-click-travel', name: "One-Click Travel", category: 'Travel' },
  { slug: 'joypreneurs', name: "Joypreneurs", category: 'Business' },
  { slug: 'first-class-technology-consulting', name: "First Class Technology Consulting", category: 'Technology' },
  { slug: 'overlook-networks', name: "Overlook Networks", category: 'Technology' },
  { slug: 'larchmont-solutions', name: "Larchmont Solutions", category: 'Business' },
  { slug: 'rocky-mountain-business-alliance', name: "Rocky Mountain Business Alliance", category: 'Business' },
  { slug: 'hayward-engineering', name: "Hayward Engineering", category: 'Business' },
  { slug: 'nicholson-business-services', name: "Nicholson Business Services", category: 'Business' },
  { slug: 'corporate-business-services', name: "Corporate Business Services", category: 'Business' },
  { slug: 'oakbrook-consultants', name: "Oakbrook Consultants", category: 'Business' },
  { slug: 'strategic-business-plans', name: "Strategic Business Plans", category: 'Business' },
  { slug: 'it-business-services', name: "IT Business Services", category: 'Business' },
  { slug: 'blessed-business', name: "Blessed Business", category: 'Business' },
  { slug: 'consultant-recruiters', name: "Consultant Recruiters", category: 'Business' },
  { slug: 'torre-fuerte-iglesia-cristiana', name: "Torre Fuerte Iglesia Cristiana", category: 'Community' },
  { slug: 'shoresmartz', name: "ShoreSmartz", category: 'Business' },
  { slug: 'schrider-consulting-group', name: "Schrider Consulting Group", category: 'Business' },
  { slug: 'adep-group', name: "ADEP Group", category: 'Business' },
  { slug: 'amercapital-real-estate-funding', name: "AmerCapital Real Estate Funding", category: 'Real Estate' },
  { slug: 'bienesraices', name: "Bienesraices", category: 'Real Estate' },
  { slug: 'ed-caballero-exceptional-properties', name: "Ed Caballero Exceptional Properties", category: 'Real Estate' },
  { slug: 'fairway-property-services', name: "Fairway Property Services", category: 'Real Estate' },
  { slug: 'fci', name: "FCI", category: 'Business' },
  { slug: 'hernandez-soffit', name: "Hernandez Soffit", category: 'Construction' },
  { slug: 'home-master-realty', name: "Home Master Realty", category: 'Real Estate' },
  { slug: 'jacobs-financial-consulting', name: "Jacobs Financial Consulting", category: 'Finance' },
  { slug: 'm-and-g-s-properties', name: "M&G's Properties", category: 'Real Estate' },
  { slug: 'main-line-planners', name: "Main Line Planners", category: 'Finance' },
  { slug: 'mantilla-international', name: "Mantilla International", category: 'Business' },
  { slug: 'marin-reconstructive-periodontics', name: "Marin Reconstructive Periodontics", category: 'Healthcare' },
  { slug: 'michael-p-schincke', name: "Michael P. Schincke", category: 'Real Estate' },
  { slug: 'now-and-then-drywall', name: "Now and Then Drywall", category: 'Construction' },
  { slug: 'answer', name: "Answer", category: 'Business' },
  { slug: 'the-gathering', name: "The Gathering", category: 'Community' },
  { slug: 'alden-property-maintenance', name: "Alden Property Maintenance", category: 'Real Estate' },
  { slug: 'batuyong-enterprises', name: "Batuyong Enterprises", category: 'Business' },
  { slug: 'billings-real-estate-group', name: "Billings Real Estate Group", category: 'Real Estate' },
  { slug: 'champion-holdings', name: "Champion Holdings", category: 'Real Estate' },
  { slug: 'cjs-property-solutions', name: "CJS Property Solutions", category: 'Real Estate' },
  { slug: 'goldie-locks-realty', name: "Goldie Locks Realty", category: 'Real Estate' },
  { slug: 'go2-contracting', name: "Go2 Contracting", category: 'Construction' },
  { slug: 'parkway-financial', name: "Parkway Financial", category: 'Finance' },
  { slug: 'charmaine-courville-realty', name: "Charmaine Courville Realty", category: 'Real Estate' },
  { slug: 'international-consultant-ltd', name: "International Consultant Ltd", category: 'Business' },
  { slug: 'iss-industrial-support-systems', name: "ISS Industrial Support Systems", category: 'Business' },
  { slug: 'home-master-realty-2', name: "Home Master Realty", category: 'Real Estate' },
  { slug: 'butler-realty-partners', name: "Butler Realty Partners", category: 'Real Estate' },
  { slug: 'intercity-realty', name: "InterCity Realty", category: 'Real Estate' },
  { slug: 'cross-realty-investment-group', name: "Cross Realty Investment Group", category: 'Real Estate' },
  { slug: 'windsor-realty-advisors', name: "Windsor Realty Advisors", category: 'Real Estate' },
  { slug: 'wilshire-realty-group', name: "Wilshire Realty Group", category: 'Real Estate' },
]

/** Filter chips, most-represented category first. */
export const portfolioCategories = [
  'All',
  ...Object.entries(
    portfolioLogos.reduce((acc, l) => ({ ...acc, [l.category]: (acc[l.category] || 0) + 1 }), {})
  )
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([name]) => name),
]
