export const resources = [
  {
    slug: 'logo-design-process',
    category: 'Logo design',
    title: 'The logo design process: from brief to final files',
    description: 'A practical, step-by-step explanation of research, concept development, revision, testing and handover in a professional logo project.',
    updated: '2026-08-03',
    readTime: '9 min read',
    service: { label: 'Logo design services', href: '/logo-design' },
    intro: 'A reliable logo process is a sequence of decisions, not a sudden flash of inspiration. Each stage removes a different kind of risk: the brief prevents a beautiful but irrelevant idea, testing exposes fragile concepts, and a disciplined handover stops a strong mark from becoming inconsistent in use.',
    takeaways: [
      'Start with business context and real-world uses, not preferred colors.',
      'Judge concepts against agreed criteria instead of personal taste alone.',
      'Test the mark small, large, in one color and in its hardest application.',
      'Finish with editable masters, exports, usage rules and written ownership terms.',
    ],
    sections: [
      { heading: '1. Discovery and the design brief', body: ['The brief should explain what the business sells, who chooses it, what alternatives customers compare, and where the identity will appear. A neighborhood contractor whose mark must work on a moving vehicle has different constraints from a software product that lives mainly in a browser tab.', 'Useful inputs include the exact business name, any tagline, audience, competitors, desired and unwanted associations, geographic reach, and a list of applications. Visual references can clarify taste, but they should be accompanied by an explanation of what works in each example.'] },
      { heading: '2. Research and positioning', body: ['Research maps the visual conventions of the category and identifies where differentiation is useful. The goal is not to make a logo unlike everything else at any cost. It is to avoid accidental imitation while retaining the signals customers need to recognize the category.', 'At this stage, the team should be able to state the design problem in one sentence. For example: make a new financial service feel established enough to trust but simple enough for first-time investors. That statement becomes a filter for every concept.'] },
      { heading: '3. Concept development', body: ['Early exploration should cover meaning, form and typography before polish. Designers sketch multiple routes, combine or discard them, and develop the strongest into coherent directions. A useful presentation explains the idea, shows the mark in context and makes the tradeoffs visible.', 'More options are not automatically better. Three distinct, well-reasoned directions are more useful than dozens of superficial variations. Each direction should solve the same brief in a genuinely different way.'] },
      { heading: '4. Feedback and refinement', body: ['Good feedback describes the problem rather than prescribing the drawing. “The type feels too playful for our buyers” gives the designer room to solve the issue; “make this letter taller” may treat a symptom while creating another problem.', 'Consolidate comments from decision-makers, rank them by importance and tie them back to the brief. Refinement then improves proportion, spacing, typography, color and the relationship between symbol and wordmark without losing the concept that made the direction distinctive.'] },
      { heading: '5. Testing and handover', body: ['Before approval, test the identity at favicon size, in black and white, on light and dark backgrounds, on a common office printer and in the most demanding real application. Check legibility, contrast, reproduction and whether the silhouette remains recognizable.', 'The final handover should include vector masters such as AI, EPS or SVG; print-ready PDF; transparent PNG; JPG; color values; font information; primary and alternate lockups; and basic spacing and minimum-size guidance. The agreement should state when ownership transfers and identify any third-party fonts or assets that have separate licenses.'] },
    ],
  },
  {
    slug: 'logo-file-formats',
    category: 'Logo design',
    title: 'Logo file formats explained: SVG, EPS, PDF, PNG and JPG',
    description: 'Choose the right logo file for websites, social media, print, signage, embroidery and vendor handoffs without losing quality.',
    updated: '2026-08-03',
    readTime: '8 min read',
    service: { label: 'Logo design services', href: '/logo-design' },
    intro: 'There is no single “high-resolution logo” that covers every job. A complete handover includes scalable vector masters for production and correctly exported raster files for everyday digital use. Knowing the difference prevents blurry signs, boxed-in logos and expensive redraws.',
    takeaways: ['Use SVG for most modern websites and digital interfaces.', 'Send EPS or print-ready PDF to printers and sign makers.', 'Use transparent PNG when a raster image must sit over a background.', 'Keep original vector masters even if your team rarely opens them.'],
    sections: [
      { heading: 'Vector and raster files', body: ['Vector artwork describes shapes mathematically, so it can scale from a business card to a building without becoming pixelated. SVG, EPS, AI and many PDFs can contain vectors. Raster files are grids of pixels; PNG, JPG and WebP are common examples.', 'A raster file can look perfect at its intended size and still fail when enlarged. Resolution cannot restore detail that was never saved. Keep the vector master as the source and export new raster sizes from it when needed.'] },
      { heading: 'When to use SVG', body: ['SVG is usually the best website format for a logo because it remains sharp on high-density screens and is often smaller than a large PNG. It also supports accessible titles and can adapt to responsive layouts.', 'Use a sanitized, production-ready SVG and provide explicit display dimensions to prevent layout shift. Some older publishing systems and social platforms do not accept SVG, so retain PNG alternatives.'] },
      { heading: 'EPS, AI and PDF for production', body: ['Commercial printers, vehicle-wrap suppliers, embroiderers and sign makers commonly request EPS, AI or PDF. These formats can preserve vector paths and professional color definitions. Ask the vendor which version and color mode they need before sending files.', 'Outline display lettering only in a production copy, not the sole master. An editable version with documented fonts makes future corrections possible. A print PDF should be checked for page size, bleed and color settings when it contains more than the logo alone.'] },
      { heading: 'PNG, JPG and WebP for everyday use', body: ['PNG supports transparency and is useful in slide decks, office documents and systems that reject SVG. Export it at the actual size needed or larger for high-density screens. JPG does not support transparency and can create visible compression around sharp logo edges.', 'WebP is efficient for photographic web images, but it is rarely necessary for a simple vector logo. Social networks generally need platform-specific PNG or JPG canvases rather than a raw transparent mark.'] },
      { heading: 'A practical handover checklist', body: ['Store primary, reversed, black and white versions in clearly named folders. Include horizontal and stacked lockups, the standalone symbol, RGB files for screens, CMYK or spot-color specifications for print, and a short read-me that tells non-designers which file to use.', 'Never treat a mockup as a final logo file. A photograph of the logo on a wall or card is a presentation image, not usable production artwork.'] },
    ],
  },
  {
    slug: 'logo-design-cost',
    category: 'Buyer guide',
    title: 'How much does logo design cost—and what are you paying for?',
    description: 'Compare DIY tools, marketplaces, freelancers and agencies by process, deliverables, rights, risk and support—not price alone.',
    updated: '2026-08-03',
    readTime: '10 min read',
    service: { label: 'View LogoOrbit pricing', href: '/pricing#logo' },
    intro: 'Logo prices vary because the thing being sold varies. A downloadable template, a contest, a single designer’s custom mark and a strategy-led identity program may all be called “logo design,” while differing sharply in research, originality, testing, deliverables and accountability.',
    takeaways: ['Define the deliverables and decision process before comparing quotes.', 'Confirm ownership, font licensing and originality in writing.', 'Budget for the identity applications you need at launch.', 'Treat unusually low prices or vague portfolios as a prompt for more due diligence.'],
    sections: [
      { heading: 'The four common buying models', body: ['DIY and automated tools prioritize speed and control but usually rely on reusable ingredients. Marketplaces widen the choice of designers, though the customer often carries more of the selection and creative-direction burden. Freelancers provide direct collaboration, with capability depending on the individual. Agencies add process, capacity and broader implementation support.', 'None of these models is automatically right or wrong. A short-lived event may not need the same investment as a company name intended to be trademarked, franchised and placed on hundreds of physical locations.'] },
      { heading: 'What changes the price', body: ['The largest drivers are research depth, number of decision-makers, geographic and category complexity, the number of identity elements, required applications, testing, timeline and the experience of the team. Naming, messaging, brand architecture and trademark counsel are separate disciplines even when sold in one engagement.', 'Revision promises should be read carefully. Unlimited changes sound reassuring, but a strong process aims for informed decisions rather than endless arbitrary variations. Ask what counts as a new direction and what happens when the brief changes.'] },
      { heading: 'Compare scope, not package names', body: ['Request an itemized list: number of initial directions, revision approach, lockups, color versions, file formats, typography and color documentation, guidelines, social assets, stationery, packaging or website work, and post-delivery support.', 'Also compare who does the work, whether you can speak with them, how originality is checked, what evidence accompanies a case study, and which rights transfer. A cheap mark that requires later reconstruction can cost more than a complete first handover.'] },
      { heading: 'Rights and hidden costs', body: ['A quote should state whether copyright transfers, when it transfers and which pre-existing or third-party elements are excluded. Fonts, stock assets and software can carry their own license terms. Trademark registration is not the same as copyright transfer, and a basic similarity search is not a legal guarantee.', 'Other costs may include rush delivery, extra applications, printing, font licenses, domain names, trademark filing fees, website hosting and future brand-governance work. Put these beside the design fee when comparing total cost.'] },
      { heading: 'Questions to ask before hiring', body: ['Ask to see relevant finished work and at least one explanation of the problem, constraints and solution—not mockups alone. Ask who will design the work, how feedback is handled, which files arrive, what support exists after launch and what happens if the project stops.', 'A credible provider should answer plainly, distinguish design opinion from legal advice and avoid promising business results that design alone cannot guarantee.'] },
    ],
  },
  {
    slug: 'brand-identity-checklist',
    category: 'Brand identity',
    title: 'Brand identity checklist: what a system should include',
    description: 'Plan the visual and practical components needed to keep a brand consistent across web, print, social media, packaging and sales materials.',
    updated: '2026-08-03',
    readTime: '11 min read',
    service: { label: 'Explore branding packages', href: '/pricing#branding-kit' },
    intro: 'A logo identifies a business; an identity system helps people produce recognizable work without reinventing every decision. The right scope depends on where the brand appears, but every useful system connects strategic intent to repeatable visual rules and real templates.',
    takeaways: ['Document the strategic choices before the visual rules.', 'Build a flexible logo system rather than one lockup.', 'Specify accessible color combinations and typography roles.', 'Test guidelines by having someone else create a real asset with them.'],
    sections: [
      { heading: 'Foundation: positioning and audience', body: ['Record the audience, category, value proposition, personality and the few associations the identity must create. This is not a long manifesto. It is the decision layer that explains why the system looks and sounds the way it does.', 'If multiple products or divisions exist, document brand architecture and naming rules early. Otherwise, every new offer can create a new visual exception.'] },
      { heading: 'Logo system and usage rules', body: ['Include primary, compact, stacked and symbol-only configurations where the applications justify them. Define clear space, minimum size, background behavior, one-color use and a small set of incorrect examples.', 'A responsive system should simplify deliberately at small sizes rather than shrinking detail until it disappears. Favicons, app icons, avatars and embroidery deserve specific tests.'] },
      { heading: 'Color, typography and accessibility', body: ['Specify values for common screen and print workflows and label which combinations are approved. Brand colors do not need to pass text contrast in every pairing, but the system must include accessible combinations for body text, controls and essential information.', 'Define type families, weights, hierarchy and fallbacks. State whether font licenses cover the intended users and environments. A substitute for office documents prevents teams from making an emergency choice later.'] },
      { heading: 'Imagery, graphics and motion', body: ['Photography direction, illustration style, icons, patterns, data visualization and motion behavior make the identity recognizable beyond the logo. Use concrete examples: subject matter, lighting, crop, composition and what to avoid.', 'Motion rules can cover easing, speed, transitions and logo animation. They should reinforce the brand’s character while respecting reduced-motion preferences.'] },
      { heading: 'Templates, governance and handover', body: ['Prioritize templates people will really use: social posts, presentations, proposals, email signatures, stationery, packaging or signage. Each one turns abstract rules into a working example.', 'Name an owner, decide where approved assets live, version the guidelines and set a review point. A short system that is maintained is more valuable than an impressive document nobody can apply.'] },
    ],
  },
  {
    slug: 'rebranding-checklist',
    category: 'Brand strategy',
    title: 'Rebranding checklist: change without losing recognition',
    description: 'A staged rebrand framework covering evidence, scope, identity development, migration, launch and measurement.',
    updated: '2026-08-03',
    readTime: '12 min read',
    service: { label: 'Start a brand project', href: '/contact' },
    intro: 'Rebranding changes an asset customers already recognize, so it should begin with evidence and end with a managed migration. The creative work is only one part. Inventory, stakeholder decisions, legal checks, accessibility, rollout sequencing and measurement determine whether the new system survives contact with the organization.',
    takeaways: ['Write the business reason and success measures before commissioning design.', 'Inventory every touchpoint before finalizing scope.', 'Separate recognition worth keeping from baggage worth removing.', 'Plan coexistence, redirects, templates and staff training before launch day.'],
    sections: [
      { heading: 'Confirm the reason to rebrand', body: ['Valid triggers include a changed strategy, merger, market expansion, confusing architecture, legal conflict or a system that cannot work in current channels. “The logo feels old” may be a symptom, not the underlying problem.', 'Set observable goals such as improved brand recognition in research, fewer sales objections, faster asset production or successful consolidation of product brands. Design cannot guarantee revenue, so keep attribution honest.'] },
      { heading: 'Audit the current brand', body: ['Collect customer and staff evidence, review competitors and catalog every asset. Record what is recognized, trusted, misunderstood and inconsistently used. The audit should include digital products, domains, listings, signage, packaging, contracts and internal systems.', 'Identify equity that should survive. Evolution can be more effective than replacement when distinctive colors, shapes, names or verbal cues already carry recognition.'] },
      { heading: 'Define scope and decision rights', body: ['Decide whether the project changes only the visual system or also positioning, name, architecture and messaging. Name the final decision-maker and create a review group small enough to work.', 'Legal availability checks should happen before commitment, especially when names or distinctive symbols change. Search results and domain availability are useful screening inputs but do not replace qualified trademark advice.'] },
      { heading: 'Build and validate the system', body: ['Develop the identity against representative applications, not a logo in isolation. Test accessible color use, small sizes, common production methods and key customer journeys. Include employees and customers in structured validation where the risk justifies it.', 'Document what changes and what remains. A clear rationale helps internal teams explain the rebrand consistently without turning the launch into a debate about personal taste.'] },
      { heading: 'Migrate, launch and measure', body: ['Create a source-of-truth asset library, replacement schedule, redirect map, vendor instructions and owner for each touchpoint. Some physical materials can run down naturally; others create confusion if both identities remain visible.', 'Measure the goals chosen at the start and watch support questions, search demand, direct traffic, conversion behavior and production errors. Schedule a 30-, 90- and 180-day review to fix adoption problems before they become permanent exceptions.'] },
    ],
  },
  {
    slug: 'website-design-brief',
    category: 'Web design',
    title: 'Writing a website brief that prevents scope creep',
    description: 'A client-ready framework for defining audiences, journeys, content, functionality, integrations, accessibility, SEO, measurement and launch ownership.',
    updated: '2026-08-03',
    readTime: '10 min read',
    service: { label: 'Website design services', href: '/website-design' },
    intro: 'A website brief does not need design jargon. It needs enough shared context to estimate the work and make decisions: why the site exists, who must accomplish what, which content and systems are involved, and what “done” means.',
    takeaways: ['Describe priority users and tasks, not a generic target audience.', 'List content ownership and integrations before estimating.', 'Make accessibility, performance and SEO acceptance criteria explicit.', 'Name post-launch owners for analytics, updates and technical maintenance.'],
    sections: [
      { heading: 'Business goal and success measures', body: ['State the primary outcome—qualified enquiries, purchases, bookings, applications, support deflection or investor confidence—and the secondary outcomes. Add current baselines if available so the team can measure change.', 'Avoid a list of unrelated ambitions. Ranking first, winning awards, doubling sales and explaining every service may require different work. Priorities help the design resolve conflicts.'] },
      { heading: 'Audiences and key journeys', body: ['For each priority audience, describe their situation, questions, objections and the action they need to complete. Then map the few journeys the site must support from entry page to outcome.', 'Include accessibility needs and device context. A field technician on a phone, a procurement team comparing suppliers and an existing customer seeking help should not be forced through the same path.'] },
      { heading: 'Content and information architecture', body: ['List current pages, content to keep, content to rewrite and missing material. Assign a subject-matter owner and approver. Content delays are one of the most common causes of launch delays because layout depends on real information.', 'Group pages by user need and define stable, descriptive URLs. Plan redirects from every valuable old URL. Navigation labels should use language visitors understand rather than internal department names.'] },
      { heading: 'Features, integrations and constraints', body: ['Specify forms, payments, search, accounts, multilingual needs, CRM, email, analytics, consent, maps and third-party tools. Note data flows, permissions and who owns each account.', 'Document platform, hosting, security, privacy and editorial workflow constraints. “Easy to update” should become specific permissions and tasks the internal team can test.'] },
      { heading: 'Quality and launch acceptance', body: ['Set expectations for supported browsers, responsive behavior, semantic HTML, keyboard access, contrast, reduced motion, structured data, metadata, canonical URLs, sitemap, robots rules, image handling and performance budgets.', 'Define review rounds, content freeze, migration, training, backups, monitoring and warranty. A launch checklist should identify who can approve, deploy and roll back.'] },
    ],
  },
  {
    slug: 'packaging-design-checklist',
    category: 'Packaging and print',
    title: 'Packaging design checklist: shelf strategy to press files',
    description: 'Plan structure, hierarchy, claims, barcodes, accessibility, materials, proofing and production handoff for retail and ecommerce packaging.',
    updated: '2026-08-03',
    readTime: '11 min read',
    service: { label: 'Discuss packaging design', href: '/contact' },
    intro: 'Packaging is brand communication, a physical interface and a regulated production artifact at the same time. A successful design must attract the right buyer, make the product easy to understand, survive manufacturing and carry every required piece of information.',
    takeaways: ['Obtain the approved dieline and printer specifications before final artwork.', 'Design hierarchy for the real viewing distance and sales channel.', 'Have qualified reviewers approve legal claims and mandatory copy.', 'Use physical proofs and production samples—not screen color alone.'],
    sections: [
      { heading: 'Channel, audience and shelf context', body: ['Photograph the competitive set in the actual channel and note what customers can see at first glance. Ecommerce thumbnails, crowded retail shelves and subscription unboxing each create different priorities.', 'Define the primary message, product variant system and information hierarchy. Buyers should identify brand, product and meaningful difference before secondary detail competes for attention.'] },
      { heading: 'Structure, dielines and materials', body: ['Use the printer or manufacturer’s approved dieline, including cut, fold, glue, bleed and safe areas. Confirm substrate, finishing, print method and tolerances because they affect color, line weight and achievable detail.', 'Sustainability claims require evidence. Consider material reduction, recyclability in the intended market, shipping efficiency and whether decoration or mixed materials undermine recovery.'] },
      { heading: 'Copy, claims and codes', body: ['Create a copy deck with hierarchy and ownership. Mandatory information differs by product and jurisdiction; have the appropriate regulatory or legal specialist approve ingredients, warnings, claims, net contents, addresses and symbols.', 'Generate barcodes from authoritative data, preserve quiet zones and test printed samples with the intended scanner. Add batch, date or variable-data areas to the production plan.'] },
      { heading: 'Legibility and accessible use', body: ['Test critical copy at physical size, under realistic lighting and on the final material. Contrast, type size, line spacing and glare all affect legibility. Do not rely on color alone to distinguish product variants or warnings.', 'Consider opening, handling and disposal as part of the experience. Instructions should be sequenced, pictograms explained where necessary and essential information available through an accessible digital route when appropriate.'] },
      { heading: 'Proofing and production handoff', body: ['Run preflight checks for fonts, linked images, overprint, spot colors, ink limits, bleeds and layers. Review a contract proof for content and color, then a structural or production sample for fit, finish and assembly.', 'Archive editable artwork, approved PDFs, dielines, color standards, copy approvals and printer notes with version numbers. Record any press-side adjustment so the next production run begins from reality rather than the original assumption.'] },
    ],
  },
]

export const resourceBySlug = Object.fromEntries(resources.map((resource) => [resource.slug, resource]))

export const glossary = [
  ['Accessibility', 'The practice of making products and communications usable by people with a wide range of abilities, devices and assistive technologies.'],
  ['Bleed', 'Artwork extended beyond a print trim line so small cutting variations do not leave an unintended white edge.'],
  ['Brand architecture', 'The relationship and naming logic between a parent brand, sub-brands, products and services.'],
  ['Brand identity', 'The coordinated verbal and visual system used to make a brand recognizable and consistent.'],
  ['Brand positioning', 'The specific place a brand aims to occupy in the audience’s mind relative to alternatives.'],
  ['Brand guidelines', 'Documented rules and examples for applying an identity consistently.'],
  ['CMYK', 'Cyan, magenta, yellow and black inks used in common commercial printing.'],
  ['Color contrast', 'The measurable difference in luminance between foreground and background colors, important for legibility.'],
  ['Creative brief', 'A concise agreement on the problem, audience, goals, constraints, deliverables and approval process.'],
  ['Dieline', 'A production template showing the cuts, folds, glue areas and safe zones of packaging.'],
  ['DPI', 'Dots per inch, a print-output measure often used informally when discussing raster image resolution.'],
  ['EPS', 'A production-oriented graphics format commonly used to exchange vector artwork with printers and sign makers.'],
  ['Favicon', 'A small site icon displayed in browser tabs, bookmarks and some search interfaces.'],
  ['Grid', 'A system of columns, rows and spacing used to align content and create visual order.'],
  ['Kerning', 'Adjustment of space between individual letter pairs.'],
  ['Leading', 'The vertical space between lines of type.'],
  ['Lockup', 'A fixed arrangement of brand elements, such as a symbol, wordmark and tagline.'],
  ['Logomark', 'A symbol used to identify a brand, with or without a wordmark.'],
  ['Mockup', 'A presentation showing how a design may look in context; it is not usually production-ready artwork.'],
  ['Negative space', 'Unoccupied space within or around design elements that shapes composition and legibility.'],
  ['Pantone', 'A proprietary standardized color-matching system frequently used to specify spot inks.'],
  ['Raster image', 'An image made from a fixed grid of pixels, such as a PNG or JPG.'],
  ['Responsive logo', 'A family of related logo configurations designed to remain clear at different sizes and contexts.'],
  ['RGB', 'Red, green and blue light values used to describe colors on screens.'],
  ['Safe area', 'The region of a design where important content can sit without risk from cropping, trimming or interface overlays.'],
  ['SVG', 'Scalable Vector Graphics, a web-friendly vector format that remains sharp at different sizes.'],
  ['Tracking', 'Uniform adjustment to spacing across a range of letters.'],
  ['Typography hierarchy', 'The use of size, weight, spacing and placement to show the relative importance of text.'],
  ['Vector graphic', 'Artwork defined by mathematical paths that can scale without pixelation.'],
  ['Visual identity', 'The visual portion of a brand system, including logo, color, typography, imagery and graphic behavior.'],
  ['WCAG', 'The Web Content Accessibility Guidelines, an international standard for accessible digital content.'],
  ['White space', 'Intentional empty space that separates elements and improves focus, hierarchy and comprehension.'],
]
